### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by codeDerleek** [Adriwin06/Ultimate-UE5-CommonUI-Full-Game-Menu-System#3]
It's far from clear how to use this project.  Partly because I've never used anyones code like this.  I would like to see how to install and customize this project.

**Comment by Adriwin06** [comment]
Hi! Thanks you for letting me know. I am aware of this, and the documentation is not finished yet. I'm still working on it, but I will try to write it faster if that's what is needed the most.

**Comment by codeDerleek** [comment]
At a minimum I need to know how you intend for me to install this to my projects.

**Comment by Adriwin06** [comment]
It will be added to the Wiki later

**Comment by Adriwin06** [comment]
I added a very detailed page on the Wiki on how to implement it on your own project, so please check it out [here](https://github.com/Adriwin06/Ultimate-UE5-CommonUI-Full-Game-Menu-System/wiki/Integrate-to-you-own-project). So no I can close this issue.
