### ISSUE TITLE
Cannot Open  Cloned Project (Plugins are incomplete)

### ISSUE THREAD

**Issue by nonamed46** [Adriwin06/Ultimate-UE5-CommonUI-Full-Game-Menu-System#5]
Hi I'm very excited to test out your project!
Cloning it from github I do run into a lot of issues trying to launch it though. I think it has to do with the default unreal engine gitignore from github because it excludes the .lib and .dll files (and possibly a few others) that are required by DLSS, FSR etc. and can't be rebuilt manually.

Sadly they are relatively big so you might have to use lfs, if you want to keep them as part of your repository. Or you could remove them entirely and maybe set up a guide how to make them work with your project.

It does open if you deactivate all the plugins but then it's not fully functional.

**Comment by Adriwin06** [comment]
Hi Thanks you so much for sharing this issue and for your interest toward my project. I was aware of an issue with plugins but I couldn't find what was causing this. I never thought of the .gitignore file🤦‍♂️. I will fix this issue in the next commit, and thanks again for making me discover the reason behind this issue. In the meantime, you can do that: https://github.com/Adriwin06/Ultimate-UE5-CommonUI-Full-Game-Menu-System/wiki/Getting-Started#if-you-have-this-missing-plugins-modules-error if you want to try it.

**Comment by Adriwin06** [comment]
Thanks again for showing me the origin of this error. I fixed it in the last two commits, so now you should be good to try it!

**Comment by nonamed46** [comment]
Awesome! thanks for your work and the quick response I'll try it out soon :D

**Comment by Adriwin06** [comment]
If you want I just published a new release with a packaged version, so it's easier for you to try it.
